name: Build and Deploy

on:
  workflow_call:

jobs:
  build:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate _config.yml
        run: |
          chmod +x .github/scripts/generate-config.sh
          .github/scripts/generate-config.sh
        env:
          REPO_URL: "https://github.com/${{ github.repository }}"
          OWNER_URL: "https://github.com/${{ github.repository_owner }}"
          REPO_NAME: "${{ github.event.repository.name }}"
          OWNER_NAME: "${{ github.repository_owner }}"
          BASEURL: "/${{ github.event.repository.name }}"

      - name: _config.yml created by generate-config.sh
        run: |
          cat _config.yml

      - name: Replace links with display button in README.md
        uses: ./
        with:
          input-file: 'README.md'
          output-file: 'index.md'
          debug: true

      - name: index.md after links to buttons conversion 
        run: |
          cat index.md 

      - name: Initialise repo to allow Jekyll to build 
        run: |
          chmod +x .github/scripts/init-jekyll.sh
          .github/scripts/init-jekyll.sh
          # Debugging the final output
          cat index.md

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
          PAGES_REPO_NWO: ${{ github.repository }} 
          
      - name: Debug Jekyll Build
        run: |
            echo "Listing files in the root directory:"
            ls -al
            echo "Listing files in the _site directory:"
            ls -al _site
  
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deploy only if build successful and in main branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() && github.ref == 'refs/heads/main' }} 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
