name: Main Workflow

on:
  push:
    branches:
      - feature/*
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  pages: write
  id-token: write

jobs:
  test:
    if: always() 
    uses: ./.github/workflows/includes/test.yml

  build:
    needs: test
    if: ${{ needs.test.result == 'success' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature/')) }}
    uses: ./.github/workflows/includes/build.yml

  deploy:
    needs: build
    if: ${{ needs.build.result == 'success' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/includes/deploy.yml
  