name: Main Workflow
run-name: ${{ github.actor }} is a Test Workflow

on:
  push:
    branches:
      - feature/*
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  pages: write
  id-token: write

jobs:
  test:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    uses: ./.github/workflows/includes/test.yml

  build:
    needs: test
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature/')) }}
    uses: ./.github/workflows/includes/build.yml

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/includes/deploy.yml
