name: Test Link-to-Button Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Create a sample README file
      run: |
        echo "# Sample Project" > README.md
        echo "" >> README.md
        echo "This is a sample project to demonstrate the link-to-button GitHub Action." >> README.md
        echo "" >> README.md
        echo "<!-- Start Button -->" >> README.md
        echo "[Run Script](https://github.com/user/repo/blob/main/script.sh)" >> README.md
        echo "<!-- End Button -->" >> README.md

    - name: Run Link-to-Button Action
      uses: ./
      with:
        input-file: 'README.md'
        output-file: 'index.md'
    
    # Work in GitHub Pages
    - name: Enable Button Functionality
      run: |
        echo "<script>" >> index.md
        cat dist/script.js >> index.md
        echo "</script>" >> index.md

    - name: Print Updated Content
      run: cat index.md

    - name: Verify Output
      run: |
        #!/bin/bash
        set -e
        if grep -q '<button data-script-name="Run Script"' index.md && grep -q 'fetchAndDisplayScript' index.md; then
          echo "Test passed: Button and script are present in index.md"
        else
          echo "Test failed: Button and/or script are missing in index.md" >&2
          exit 1
        fi
